# Generated by Django 5.1.6 on 2025-03-25 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_rename_orginal_price_listing_original_price_and_more'),
        ('message', '0003_initial'),
        ('user', '0003_user_purdueverificationlastsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='listing',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_room', to='user.user')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
                ('messages', models.ManyToManyField(to='message.message')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_room', to='user.user')),
            ],
            options={
                'unique_together': {('seller', 'buyer', 'listing')},
            },
        ),
    ]
