# Generated by Django 5.1.6 on 2025-03-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_remove_message_listing_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='messages',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='room',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='room',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='room',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
