# Generated by Django 5.1.6 on 2025-04-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
