# Generated by Django 5.1.6 on 2025-02-20 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('orginal_price', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hidden', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('dateListed', models.DateTimeField(auto_now_add=True)),
                ('sold', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
