# Generated by Django 5.1.6 on 2025-03-23 17:42

import django.core.validators
import django.db.models.deletion
import listing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_alter_user_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('original_price', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('dateListed', models.DateTimeField(auto_now_add=True)),
                ('sold', models.BooleanField(default=False)),
                ('media', models.FileField(upload_to=listing.models.listing_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mov'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
