# Generated by Django 5.1.6 on 2025-03-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
    ]
