# Generated by Django 5.1.6 on 2025-03-23 18:27

import django.core.validators
import django.db.models.deletion
import listing.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_recreate_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='media',
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=listing.models.listing_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mov'])])),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='listing.listing')),
            ],
        ),
    ]
