# Generated by Django 5.1.6 on 2025-04-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listing", "0003_remove_listing_media_listingmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="location",
            field=models.CharField(default="other", max_length=255),
        ),
    ]
