# Generated by Django 5.1.6 on 2025-04-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_listing_location'),
        ('user', '0005_alter_user_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='saves',
        ),
        migrations.AddField(
            model_name='listing',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='saved_listings', to='user.user'),
        ),
    ]
