# Generated by Django 5.1.6 on 2025-04-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_remove_listing_saves_listing_saves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='saves',
            new_name='saved_by',
        ),
    ]
