# Generated by Django 5.1.6 on 2025-04-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_rename_saves_listing_saved_by'),
        ('report', '0002_alter_report_listing'),
        ('user', '0008_history'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('user', 'reported_user'), name='unique_report_per_user_pair'),
        ),
    ]
