# Generated by Django 5.1.6 on 2025-05-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
