# Generated by Django 5.1.6 on 2025-02-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_purdueverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purdueVerificationLastSent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
