# Generated by Django 5.1.6 on 2025-03-23 01:42

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_purdueverificationlastsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_profile_picture_path),
        ),
    ]
