# Generated by Django 5.1.6 on 2025-04-15 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listing", "0006_rename_saves_listing_saved_by"),
        ("user", "0007_remove_user_blocked_user_blockedusers"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listing.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewed_listings",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
                "unique_together": {("user", "listing")},
            },
        ),
    ]
