# Generated by Django 5.1.6 on 2025-04-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="appeal",
            field=models.TextField(blank=True, null=True),
        ),
    ]
