# Generated by Django 5.1.6 on 2025-05-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numberOfReviews',
            field=models.IntegerField(default=0),
        ),
    ]
