# Generated by Django 5.1.6 on 2025-05-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_numberofreviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='numberOfReviews',
        ),
    ]
